openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://localhost:7072"
paths:
  /customers:
    get:
      summary: "GET customers"
      responses:
        "200":
          description: "OK"
    put:
      summary: "PUT customers"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST customers"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE customers"
      responses:
        "200":
          description: "OK"
components:
  schemas:
